### ISSUE TITLE
[ERROR] TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by usingthisforreasons** [charlesbel/Microsoft-Rewards-Farmer#258]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

It keeps saying this error, I updated my selenium and have chrome installed

### Copy and paste your error

2023-08-12 21:05:11,524 [ERROR] TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### Screenshots

.

### Value of dashboard variable

.

**Comment by charlesbel** [comment]
make sure every packages is updated to the latest version : ```pip install selenium selenium-wire undetected-chromedriver --upgrade```

**Comment by joshuamooree** [comment]
Something else I noted was that vcredist is required for some of the modules and you don't necessarily get it by default.  I was getting errors on one of the VMs (clean, base install of Windows 10) I run this in related to "DLL Load failed while importing _brotli: the specified module could not be found".  Turned out after I install the latest 32 and 64 bit vcredist files from Microsoft that went away.

**Comment by charlesbel** [comment]
Closing, you're welcome to reopen
